name: omicverse_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - pytables
  - pytorch
  - pip:
    - streamlit
    - omicverse
    - scanpy
    - leidenalg
    - openpyxl
    - torch-geometric
